### ISSUE TITLE
一种特殊字体的想法

### ISSUE THREAD

**Issue by ChihSee-Hsie** [lxgw/LxgwNeoZhiSong#1]
首先对 LXGW 大佬的开源精神和不懈努力致以敬意，您的工作为中文字体排印贡献良多。

接下来是一个想法：在中文古籍排印中，有一种特殊的注解称为双行夹注。这种注解使用的字体高度和正文基本一致（或者略小于正文），而宽度是正文的一半左右。具体见下：

[图引自书格提供《东莱先生增入正义音注史记详节》](https://new.shuge.org/wp-content/uploads/2021/07/dong_lai_xian_sheng_shi_ji_xiang_jie02-1000x924.jpg)

当然上述排版也不能代表整体情况，因为许多古籍中的夹注字体，其高度其实比图中还要小一点——但基本都是瘦高形状的字体。在比较现代的排版中，类似的情况可在[中华书局1959年出版的《古文观止》](https://item.jd.com/11592508.html)中找到。现在一些排版使用普通的字体，为容纳两行则只能将夹注的字体大小设置为正文的一半，这样在普通字体宽高基本一致的情况下字面变得只有正文的四分之一了。我出于个人兴趣作排版时遇到了这样的情况，曾经尝试用软件将普通字体改窄一半，但效果十分难堪，故在这里提出一个 issue，俟公参考。如公有意，或许又是一个开拓。

**Comment by lakejason0** [comment]
如果是非开源字体的话，也就是需要瘦高的字体？汉仪清雅、汉仪典雅、汉仪长宋等其实都是较瘦高的字体，不知道与您所想的瘦高是否相同？

**Comment by ChihSee-Hsie** [comment]
> 汉仪典雅

您好，感谢推荐。我试了一下，感觉这些字体的窄主要体现在「字面率小」这一点上，字框没有大的变动。但「汉仪长仿宋体」似乎不一样，这款字体的字框确实更窄。

**Comment by lxgw** [comment]
目前该字体没有制作瘦长版本的计划，请您谅解。
