### ISSUE TITLE
关于英文标点的问题

### ISSUE THREAD

**Issue by MisakaMikoto9982** [lxgw/LxgwNeoZhiSong#4]
用猫啃网的字体做了一套WORD模板，其中正文样式就是霞鹜新致宋，当我整理python笔记时，发现愣是打不了英文标点。我分别排除了操作系统、文字处理软件、输入法、模板等一堆问题后，发现罪魁祸首竟然是字体。嗯，用空白模板新建文档，不论是WORD还是WPS，不管原字体下如何设置，一旦更换字体为霞鹜新致宋，英文的标点就被改成中文标点，但是在记事本或者notepad--这种不支持修改字体的软件里就一切正常。原以为是字体没有做英文标点，毕竟我就调用不出来，但现在看起来更像是字体的Bug
使用系统：win11 22h2 22621.2215
测试软件：
WPS-11.8.2.12089 官网企业版
word——office365 版本 2308 Build 16.0.16731.20052
VS Code——1.81.1 发布于8月9日
微软拼音——系统内置
Rime——weasel-0.15.0.0
字体版本——霞鹜新致宋0.112 发布于8月22日
等下重启设备录个屏，为了方便会用网盘传输，拟定是123网盘或蓝奏云

**Comment by MisakaMikoto9982** [comment]
结案了，事实是在WORD或WPS中，不论用任何字体，都无法输出英文标点，除霞鹜新致宋外，还测试过等线、得意黑、朱雀仿宋等五六款字体，确认现象是这样。但在记事本、notepad--、vs code这种不支持修改字体的软件里就一切正常，因为这种问题实在过于离谱，我此前编辑另外几篇数万和数十万字的文稿时都没有发现过。针对WORD或WPS无法输出英文标点的问题，我在这里反馈前就去百度过，但一无所获，之后就误会到这款字体上了，没有切换到其他的字体重新试验。
但在WORD或WPS无法输出英文标点这种bug就离谱，有7年网龄的我完全是闻所未闻，这没有十年脑血栓哪里能想得到，，，接下来只能重新折腾一遍输入法，或者用单独纯英文字体显示英文内容了

**Comment by lxgw** [comment]
Microsoft 365 Word 没有问题。

![image](https://github.com/lxgw/LxgwNeoZhiSong/assets/51902309/83e923e4-e2d3-4c9c-8a95-55b06e4b0542)

**Comment by NightFurySL2001** [comment]
请提供所谓的“英文标点”是哪几个特定的符号，若可以提供 Unicode 码位会更好。

其中比较麻烦的特例是弯引号（“‘ ’”）和省略号（……），这两个符号在 Unicode 中定义中英是使用同一个码位，但是在中文字体必须为全宽，而英文字体一般为比例宽度。如果在 Word 输入的话，需要注意中西文字体是可以分开设置，如下：
![image](https://github.com/lxgw/LxgwNeoZhiSong/assets/33471049/4d9f7878-cf36-409d-886d-bbebe79dbcbf)
